#
# Makefile for the linux NOVA filesystem routines.
#

obj-$(CONFIG_NOVA_FS) += nova.o

nova-y := balloc.o bbuild.o dax.o dir.o file.o inode.o journal.o log.o namei.o\
	  rebuild.o stats.o super.o symlink.o
